//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendetfactura
    {
        public int Documento { get; set; }
        public int secuencia { get; set; }
        public string articulo { get; set; }
        public string nombre { get; set; }
        public decimal Precio { get; set; }
        public double Descuento { get; set; }
        public decimal impuesto { get; set; }
        public string totallinea { get; set; }
    
        public virtual inv_articulo inv_articulo { get; set; }
        public virtual venfactura venfactura { get; set; }
    }
}
